-- ==========================================
-- Supabase Schema for Offline-First POS
-- Copy and paste this into your Supabase SQL Editor
-- ==========================================

-- 1. Create Tables
CREATE TABLE businesses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    expiry_date BIGINT NOT NULL, -- Stored as JS Timestamp
    status TEXT NOT NULL DEFAULT 'active'
);

CREATE TABLE devices (
    device_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    last_synced BIGINT DEFAULT 0
);

CREATE TABLE products (
    id UUID PRIMARY KEY, -- ID generated by Dexie locally
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price DECIMAL NOT NULL,
    cost_price DECIMAL NOT NULL DEFAULT 0,
    quantity INT NOT NULL DEFAULT 0,
    low_stock_threshold INT NOT NULL DEFAULT 5,
    updated_at BIGINT NOT NULL
);

CREATE TABLE sales (
    id UUID PRIMARY KEY, -- ID generated by Dexie locally
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    receipt_id TEXT NOT NULL,
    total DECIMAL NOT NULL,
    total_profit DECIMAL NOT NULL,
    timestamp BIGINT NOT NULL,
    items JSONB NOT NULL
);

CREATE TABLE purchases (
    id UUID PRIMARY KEY, -- ID generated by Dexie locally
    business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
    total DECIMAL NOT NULL,
    timestamp BIGINT NOT NULL,
    items JSONB NOT NULL
);

-- ==========================================
-- 2. Row Level Security (Data Isolation)
-- ==========================================
ALTER TABLE businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchases ENABLE ROW LEVEL SECURITY;

-- Production Security Policies
CREATE POLICY "Users can access their own business" ON businesses 
    FOR ALL USING (id = auth.uid());

CREATE POLICY "Users can manage devices for their business" ON devices 
    FOR ALL USING (business_id = auth.uid());

CREATE POLICY "Users can access their products" ON products 
    FOR ALL USING (business_id = auth.uid());

CREATE POLICY "Users can access their sales" ON sales 
    FOR ALL USING (business_id = auth.uid());

CREATE POLICY "Users can access their purchases" ON purchases 
    FOR ALL USING (business_id = auth.uid());

-- ==========================================
-- 3. Stock Delta Merge Function (RPC)
-- ==========================================
-- Prevents stock race conditions when 2 offline POS devices sell the same item.
-- Instead of last-write-wins, we apply a mathematical delta (e.g. quantity - 2).

CREATE OR REPLACE FUNCTION apply_stock_delta(
  p_product_id UUID,
  p_business_id UUID,
  p_quantity_change INT
) RETURNS void AS $$
BEGIN
  UPDATE products 
  SET quantity = quantity + p_quantity_change,
      updated_at = extract(epoch from now()) * 1000
  WHERE id = p_product_id AND business_id = p_business_id;
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- 4. Server Time Function (RPC)
-- ==========================================
-- Securely fetch the server's Unix timestamp to prevent local clock tampering.

CREATE OR REPLACE FUNCTION get_server_timestamp() 
RETURNS BIGINT AS $$
BEGIN
  RETURN extract(epoch from now()) * 1000;
END;
$$ LANGUAGE plpgsql;
